[package]
name = "snapshot-editor"
version = "1.5.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
build = "../../build.rs"
license = "Apache-2.0"

[[bin]]
name = "snapshot-editor"
bench = false

[dependencies]
clap = { version = "4.4.1", features = ["derive", "string"] }
clap-num = "1.0.2"
libc = "0.2.147"
snapshot = { path = "../snapshot" }
thiserror = "1.0.44"
vmm = { path = "../vmm" }

fc_utils = { package = "utils", path = "../utils" }
