[package]
name = "mmds"
version = "0.1.0"
authors = ["Amazon firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
json-patch = ">=0.2.1"
lazy_static = ">=1.1.0"
serde_json = ">=1.0.9"

micro_http = { path = "../micro_http" }
