version: 2
updates:
  - package-ecosystem: "cargo" 
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels: 
      - "Status: Awaiting review"
    allow:
      - dependency-type: "all"
    open-pull-request-limit: 100
