[package]
name = "firecracker"
version = "0.4.0"
authors = ["Amazon firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
clap = "=2.27.1"

api_server = { path = "api_server" }
logger = { path = "logger"}
vmm = { path = "vmm" }

[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"

[workspace]
