[package]
name = "firecracker"
version = "0.2.0"
authors = ["Amazon firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
clap = "=2.27.1"

api_server = { path = "api_server" }
devices = { path = "devices" }
net_util = { path = "net_util" }
sys_util = { path = "sys_util" }
vmm = { path = "vmm" }
logger = { path = "logger" }

[profile.release]
lto = true

[workspace]
