[package]
name = "firecracker"
version = "0.10.1"
authors = ["Amazon firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
backtrace = {version = "0.3", features = ["libunwind", "libbacktrace"], default-features = false}
chrono = ">=0.4"
clap = "=2.27.1"
serde_json = ">=1.0.9"

api_server = { path = "api_server" }
jailer = { path = "jailer" }
logger = { path = "logger"}
mmds = { path = "mmds" }
seccomp = { path = "seccomp" }
vmm = { path = "vmm" }
fc_util = { path = "fc_util" }

[dev-dependencies]
tempfile = ">=3.0.2"

[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"

[features]
vsock = ["api_server/vsock"]

[workspace]
