[package]
name = "firecracker"
version = "0.1.0"
authors = ["Amazon firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
clap = "=2.27.1"

api_server_v2 = { path = "api_server_v2" }
devices = { path = "devices" }
sys_util = { path = "sys_util" }
vmm = { path = "vmm" }

[workspace]
