[package]
name = "firecracker"
version = "0.8.0"
authors = ["Amazon firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
clap = "=2.27.1"

api_server = { path = "api_server" }
data_model = { path = "data_model" }
jailer = { path = "jailer" }
logger = { path = "logger"}
mmds_glue = { path = "mmds_glue" }
seccomp = { path = "seccomp" }
vmm = { path = "vmm" }

[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"

[workspace]
