[package]
name = "cpu-template-helper"
version = "1.6.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cpu-template-helper"
bench = false

[dependencies]
clap = { version = "4.4.6", features = ["derive", "string"] }
displaydoc = "0.2.4"
libc = "0.2.149"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.50"

vmm = { path = "../vmm" }

[dev-dependencies]
utils = { path = "../utils" }
