[package]
name = "cpu-template-helper"
version = "1.8.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "cpu-template-helper"
bench = false

[dependencies]
clap = { version = "4.5.4", features = ["derive", "string"] }
displaydoc = "0.2.4"
libc = "0.2.154"
log-instrument = { path = "../log-instrument", optional = true }
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
thiserror = "1.0.59"

vmm = { path = "../vmm" }
vmm-sys-util = { version = "0.12.1", features = ["with-serde"] }

[features]
tracing = ["log-instrument", "vmm/tracing"]

[lints]
workspace = true
