[package]
name = "arch"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
kvm-bindings = { git = "https://github.com/firecracker-microvm/kvm-bindings", tag = "v0.2.0-2", features = ["fam-wrappers"] }
kvm-ioctls = { git = "https://github.com/firecracker-microvm/kvm-ioctls", tag = "v0.5.0-2" }
libc = ">=0.2.39"
vm-memory = { path = "../vm-memory" }
arch_gen = { path = "../arch_gen" }
utils = { path = "../utils" }

[dev-dependencies]
device_tree = ">=1.1.0"
