[package]
name = "logger"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"

[dependencies]
lazy_static = ">=1.2"
libc = ">=0.2.39"
log = { version = ">=0.4", features = ["std"] }
serde = { version = ">=1.0.27", features = ["derive"] }
serde_json = ">=1.0.9"

utils = { path = "../utils" }

