[tool.poetry]
name = "tool.poetry"
version = "0.1.0"
description = "Firecracker python dependencies"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "*"
botocore = "*"
dataclasses = "*"
nsenter = "*"
psutil = "*"
black = "*"
pylint = "*"
pytest = "*"
pytest-timeout = "*"
PyYAML = "*"
requests = "*"
requests-unixsocket = "*"
retry = "*"
typing-extensions = "*"
gitlint = "*"
pandas = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
