[package]
name = "mmds"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
lazy_static = ">=1.1.0"
serde_json = ">=1.0.9"

micro_http = { path = "../micro_http" }
utils = { path = "../utils" }
logger = { path = "../logger" }
dumbo = { path = "../dumbo" }
snapshot = { path = "../snapshot" }
versionize = { git = "https://github.com/firecracker-microvm/versionize", tag = "v0.1.0" }
versionize_derive = { git = "https://github.com/firecracker-microvm/versionize_derive", tag = "v0.1.0" }
