[package]
name = "mmds"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
lazy_static = ">=1.1.0"
serde_json = ">=1.0.9"
versionize = ">=0.1.6"
versionize_derive = ">=0.1.3"

dumbo = { path = "../dumbo" }
logger = { path = "../logger" }
micro_http = { git = "https://github.com/firecracker-microvm/micro-http", rev = "0a58eb1" }
snapshot = { path = "../snapshot" }
utils = { path = "../utils" }
