[package]
name = "mmds"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
aes-gcm = "0.9.4"
base64 = "0.13.0"
bincode = "1.2.1"
lazy_static = ">=1.1.0"
serde = { version = ">=1.0.27", features = ["derive"] }
serde_json = ">=1.0.9"
versionize = ">=0.1.6"
versionize_derive = ">=0.1.3"

dumbo = { path = "../dumbo" }
logger = { path = "../logger" }
micro_http = { git = "https://github.com/firecracker-microvm/micro-http", rev = "0a58eb1" }
snapshot = { path = "../snapshot" }
utils = { path = "../utils" }
