[package]
name = "fc_util"
version = "0.1.0"
authors = ["Amazon firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
libc = ">=0.2.39"
time = ">=0.1.39"
timerfd = "1.0"

logger = { path = "../logger" }
