[package]
name = "snapshot"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
autobenches = false
license = "Apache-2.0"

[dependencies]
libc = "0.2"
versionize = ">=0.1.6"
versionize_derive = ">=0.1.3"
thiserror = "1.0.32"

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "version_map"
harness = false
