[package]
name = "snapshot"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"
autobenches = false

[dependencies]
libc = "0.2"
versionize = "0.1.2"
versionize_derive = ">=0.1.1"

#[[bench]]
#name = "main"
#harness = false
