[package]
name = "snapshot"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
autobenches = false
license = "Apache-2.0"

[lib]
bench = false

[dependencies]
libc = "0.2.117"
versionize = "0.1.10"
versionize_derive = "0.1.5"
thiserror = "1.0.32"
tracing = { version = "0.1.37", features = ["attributes"] }

[dev-dependencies]
criterion = { version = "0.5.0", default-features = false }

[[bench]]
name = "version_map"
harness = false
