[package]
name = "vmm"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
event-manager = ">=0.2.1"
kvm-bindings = { version = ">=0.5.0", features = ["fam-wrappers"] }
kvm-ioctls = ">=0.9.0"
lazy_static = ">=1.4.0"
libc = ">=0.2.39"
linux-loader = ">=0.4.0"
serde = { version = ">=1.0.27", features = ["derive"] }
serde_json = ">=1.0.9"
versionize = ">=0.1.6"
versionize_derive = ">=0.1.3"
vm-superio = ">=0.4.0"

arch = { path = "../arch" }
devices = { path = "../devices" }
logger = { path = "../logger" }
mmds = { path = "../mmds" }
rate_limiter = { path = "../rate_limiter" }
seccompiler = { path = "../seccompiler" }
snapshot = { path = "../snapshot"}
utils = { path = "../utils" }
virtio_gen = { path = "../virtio_gen" }
vm-memory = { path = "../vm-memory" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
cpuid = { path = "../cpuid" }

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "main"
harness = false
