[package]
name = "vmm"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"

[dependencies]
kvm-bindings = { git = "https://github.com/firecracker-microvm/kvm-bindings", tag = "v0.2.0-2", features = ["fam-wrappers"] }
kvm-ioctls = { git = "https://github.com/firecracker-microvm/kvm-ioctls", tag = "v0.5.0-2" }
lazy_static = "1.4.0"
libc = ">=0.2.39"
serde = { version = ">=1.0.27", features = ["derive"] }
serde_json = ">=1.0.9"
sysconf = "0.3.4"
versionize = { version = "0.1.1" }
versionize_derive = { git = "https://github.com/firecracker-microvm/versionize_derive", tag = "v0.1.0" }

arch = { path = "../arch" }
devices = { path = "../devices" }
kernel = { path = "../kernel" }
logger = { path = "../logger" }
vm-memory = { version = ">=0.2.2", features = ["backend-mmap"] }
mmds = { path = "../mmds" }
rate_limiter = { path = "../rate_limiter" }
seccomp = { path = "../seccomp" }
polly = { path = "../polly" }
snapshot = { path = "../snapshot"}
utils = { path = "../utils" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
cpuid = { path = "../cpuid" }
