[package]
name = "vmm"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[lib]
bench = false

[dependencies]
aws-lc-rs = "1.0.2"
bitflags = "2.0.2"
derive_more = { version = "0.99.17", default-features = false, features = ["from", "display"] }
event-manager = "0.4.0"
kvm-bindings = { version = "0.7.0", features = ["fam-wrappers"] }
kvm-ioctls = "0.16.0"
lazy_static = "1.4.0"
libc = "0.2.117"
memfd = "0.6.3"
linux-loader = "0.10.0"
serde = { version = "1.0.136", features = ["derive", "rc"] }
semver = { version = "1.0.17", features = ["serde"] }
serde_json = "1.0.78"
timerfd = "1.5.0"
thiserror = "1.0.32"
displaydoc = "0.2.4"
userfaultfd = "0.7.0"
versionize = "0.2.0"
versionize_derive = "0.1.6"
vhost = { version = "0.10.0", features = ["vhost-user-frontend"] }
vm-allocator = "0.1.0"
vm-superio = "0.7.0"
vm-memory = { version = "0.13.1", features = ["backend-mmap", "backend-bitmap"] }
log = { version = "0.4.17", features = ["std", "serde"] }
aes-gcm =  { version = "0.10.1", default-features = false, features = ["aes"] }
base64 = "0.21.0"
bincode = "1.2.1"
micro_http = { git = "https://github.com/firecracker-microvm/micro-http" }
log-instrument = { path = "../log-instrument", optional = true }

seccompiler = { path = "../seccompiler" }
snapshot = { path = "../snapshot"}
utils = { path = "../utils" }
smallvec = "1.11.2"

[target.'cfg(target_arch = "aarch64")'.dependencies]
vm-fdt = "0.2.0"

[dev-dependencies]
criterion = { version = "0.5.0", default-features = false }
device_tree = "1.1.0"
proptest = { version = "1.0.0", default-features = false, features = ["std"] }
itertools = "0.12.0"

[features]
tracing = ["log-instrument"]

[[bench]]
name = "cpu_templates"
harness = false
