[package]
name = "dumbo"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"

[dependencies]
bitflags = ">=1.0.4"

utils = { path = "../utils" }
logger = { path = "../logger" }
micro_http = { git = "https://github.com/firecracker-microvm/micro-http", rev = "49240ce" }

[dev-dependencies]
serde_json = ">=1.0.9"
