[package]
name = "dumbo"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
bitflags = ">=1.0.4"
serde = ">=1.0.27"

utils = { path = "../utils" }
logger = { path = "../logger" }
micro_http = { path = "../micro_http" }

[dev-dependencies]
serde_json = ">=1.0.9"
