[package]
name = "static_templates"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
vmm = { path = "../vmm" }

[dev-dependencies]
kvm-bindings = { version = "0.6.0", features = ["fam-wrappers"] }
serde_json = "1.0.78"
