[package]
name = "seccompiler"
version = "1.11.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
description = "Program that compiles multi-threaded seccomp-bpf filters expressed as JSON into raw BPF programs, serializing them and outputting them to a file."
homepage = "https://firecracker-microvm.github.io/"
license = "Apache-2.0"

[lib]
bench = false

[[bin]]
name = "seccompiler-bin"
path = "src/bin.rs"
bench = false

[dependencies]
bincode = "1.2.1"
clap = { version = "4.5.21", features = ["derive", "string"] }
displaydoc = "0.2.5"
libc = "0.2.168"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
thiserror = "2.0.7"
zerocopy = { version = "0.8.13" }

[lints]
workspace = true
