[package]
name = "devices"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
byteorder = ">=1.2.1"
epoll = "=2.1.0"
libc = ">=0.2.39"

dumbo = { path = "../dumbo" }
logger = { path = "../logger" }
memory_model = { path = "../memory_model" }
net_util = { path = "../net_util" }
net_sys = { path = "../net_sys" }
rate_limiter = { path = "../rate_limiter" }
sys_util = { path = "../sys_util" }
virtio_sys = { path = "../virtio_sys" }

[dev-dependencies]
tempfile = ">=3.0.2"
