[package]
name = "devices"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
byteorder = "=1.2.1"
epoll = "=2.1.0"
libc = ">=0.2.39"

fc_util = { path = "../fc_util" }
logger = { path = "../logger" }
net_util = { path = "../net_util" }
net_sys = { path = "../net_sys" }
sys_util = { path = "../sys_util" }
virtio_sys = { path = "../virtio_sys" }

[dev-dependencies]
memory_model = { path = "../memory_model"}
tempfile = ">=3.0.2"
