[package]
name = "devices"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
byteorder = "=1.2.1"
epoll = "=2.1.0"
libc = "=0.2.32"

net_util = { path = "../net_util" }
net_sys = { path = "../net_sys" }
sys_util = { path = "../sys_util" }
virtio_sys = { path = "../virtio_sys" }
vhost_sys = { path = "../vhost_sys" }
vhost_backend = { path = "../vhost_backend" }

[dev-dependencies]
data_model = { path = "../data_model"}
