[package]
name = "micro_http"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"

[dependencies]
libc = ">=0.2.39"

utils = { path = "../utils" }
logger = { path = "../logger" }