[package]
name = "kvm"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
byteorder = "=1.2.1"
libc = "=0.2.32"

kvm_sys = { path = "../kvm_sys" }
sys_util = { path = "../sys_util" }
