[package]
name = "kvm"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
kvm_wrapper = ">=0.1.0"
libc = ">=0.2.39"

memory_model = { path = "../memory_model" }
sys_util = { path = "../sys_util" }

[dev-dependencies]
byteorder = ">=1.2.1"
