[package]
name = "utils"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"

[dependencies]
libc = ">=0.2.39"
vmm-sys-util = ">=0.6.1"

net_gen = { path = "../net_gen" }
