[package]
name = "utils"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"

[dependencies]
libc = ">=0.2.39"
serde = ">=1.0.27"
vmm-sys-util = ">=0.6.1"

net_gen = { path = "../net_gen" }


[dev-dependencies]
serde_json = ">=1.0.9"

