[package]
name = "utils"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
libc = ">=0.2.39"
serde = { version = ">=1.0.27", features = ["derive"] }
vmm-sys-util = ">=0.8.0"
derive_more = { version = "0.99.17", default-features = false, features = ["from"] }

net_gen = { path = "../net_gen" }

[dev-dependencies]
serde_json = ">=1.0.9"
