[package]
name = "utils"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[lib]
bench = false

[dependencies]
derive_more = { version = "0.99.17", default-features = false, features = ["from"] }
libc = "0.2.147"
serde = { version = "1.0.165", features = ["derive"] }
thiserror = "1.0.32"
displaydoc = "0.2.4"
vmm-sys-util = "0.12.1"
vm-memory = { version = "0.14.1", features = ["backend-mmap", "backend-bitmap"] }
log-instrument = { path = "../log-instrument", optional = true }

[dev-dependencies]
serde_json = "1.0.99"

[features]
tracing = ["log-instrument"]

[lints]
workspace = true
