[package]
name = "utils"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
bincode = "1.2.1"
libc = ">=0.2.39"
net_gen = { path = "../net_gen" }
seccompiler = ">=0.2.0"
serde = { version = ">=1.0.27", features = ["derive"] }
vmm-sys-util = ">=0.8.0"

[dev-dependencies]
serde_json = ">=1.0.9"
