[package]
name = "utils"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
libc = "0.2.117"
serde = { version = "1.0.136", features = ["derive"] }
versionize = "0.1.6"
versionize_derive = "0.1.3"
vmm-sys-util = "0.11.0"
derive_more = { version = "0.99.17", default-features = false, features = ["from"] }

net_gen = { path = "../net_gen" }

[dev-dependencies]
serde_json = "1.0.78"
