[package]
name = "utils"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[lib]
bench = false

[dependencies]
displaydoc = "0.2.5"
libc = "0.2.169"
log-instrument = { path = "../log-instrument", optional = true }
thiserror = "2.0.9"

[features]
tracing = ["log-instrument"]

[lints]
workspace = true
