[package]
name = "seccomp"
version = "0.1.0"
authors = ["Amazon firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
libc = ">=0.2.39"

logger = { path = "../logger" }
sys_util = { path = "../sys_util" }
