[package]
name = "rebase-snap"
version = "1.5.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
build = "../../build.rs"
license = "Apache-2.0"

[[bin]]
name = "rebase-snap"
bench = false

[dependencies]
libc = "0.2.146"

utils = { path = "../utils" }
