[package]
name = "io_uring"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
vm-memory = { version = "0.7.0", features = ["backend-mmap"] }
