[package]
name = "vmm"
version = "0.1.0"
authors = ["Amazon firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
libc = "=0.2.32"
epoll = "=2.1.0"
scopeguard = "=0.3.3"

api_server_v2 = { path = "../api_server_v2" }
kvm = { path = "../kvm" }
kvm_sys = { path = "../kvm_sys" }
sys_util = { path = "../sys_util" }
kernel_loader = { path = "../kernel_loader" }
x86_64 = { path = "../x86_64" }
devices = { path = "../devices" }
