[package]
name = "cpuid"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"

[dependencies]
kvm-bindings = { version = "0.3.0", features = ["fam-wrappers"] }
kvm-ioctls = { version = "0.6.0" }

utils = { path = "../utils"}
