[package]
name = "cpuid"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
kvm-bindings = { version = ">=0.2", features = ["fam-wrappers"] }
kvm-ioctls = ">=0.3"
vmm-sys-util = ">=0.2.1"
