[package]
name = "api_server"
version = "0.1.0"
authors = ["Amazon firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
futures = "=0.1.18"
hyper = "=0.11.16"
serde = "=1.0.27"
serde_derive = "=1.0.27"
serde_json = "=1.0.9"
tokio-core = "=0.1.12"
tokio-uds = "=0.1.7"

fc_util = { path = "../fc_util" }
sys_util = { path = "../sys_util" }
