[package]
name = "api_server"
version = "0.1.0"
authors = ["Amazon firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
clap = "=2.27.1"
futures = "=0.1"
iron = "=0.5"

api = { path = "../api" }
sys_util = { path = "../sys_util" }
vmm = { path = "../vmm" }
