[package]
name = "jailer"
version = "0.19.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
clap = { version = ">=2.27.1", default-features = false}
libc = ">=0.2.39"
regex = ">=1.0.0"

utils = { path = "../utils" }

[dev-dependencies]
tempfile = ">=3.0.2"
