[package]
name = "jailer"
version = "0.25.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"
build = "../../build.rs"
description = "Process for starting Firecracker in production scenarios; applies a cgroup/namespace isolation barrier and then drops privileges."
homepage = "https://firecracker-microvm.github.io/"
license = "Apache-2.0"

[dependencies]
libc = ">=0.2.39"
regex = ">=1.0.0"

utils = { path = "../utils" }
