[package]
name = "sys_util"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
build = "build.rs"

[dependencies]
libc = "=0.2.32"

syscall_defines = { path = "../syscall_defines" }
data_model = { path = "../data_model" }

[build-dependencies]
gcc = "=0.3.54"
