swagger: '2.0'
info:
  title: Firecracker Instance Action API
  description: |
    The instance action section of the Firecracker API.
    An action is a request for a mutation that will have visible effect some time in the future.
    Typically a client will create an action, and then poll the state of the resource on which the action was taken to observe the effect.
    Firecracker will only maintain a fixed-size list of the N most recent action requests
      for each instance.
  version: experimental
basePath: /api-v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /actions:
    get:
      summary: Return the list of (most recent) actions for an instance.
      operationId: listInstanceActions
      responses:
        200:
          description: The (most recent) instance actions listed by action identifier.
          schema:
            type: array
            items:
              type: string
        default:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
  /action/{action_id}:
    get:
      summary: Return detailed information about an action.
      operationId: describeInstanceAction
      parameters:
      - name: action_id
        in: path
        description: The action identifier.
        required: true
        type: string
      responses:
        200:
          description: The instance action information.
          schema:
            $ref: '#/definitions/InstanceActionInfo'
        default:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: Create an instance action.
      operationId: createInstanceAction
      parameters:
      - name: action_id
        in: path
        description: The action identifier.
        required: true
        type: string
      - name: info
        in: body
        required: true
        schema:
          $ref: '#/definitions/InstanceActionInfo'
      responses:
        201:
          description: No previous action existed so a new one was created.
        204:
          description: Action updated.
        default:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
definitions:
  InstanceActionInfo:
    type: object
    description: |
      Variant wrapper containing the real action.
      For listInstanceActions, only action_id will be populated.
      instance_device_detach_action will only be present if action_type is InstanceDeviceDetach.
    required:
      - action_id
    properties:
      action_id:
        type: string
        minLength: 1
        maxLength: 64
      action_type:
        description: Enumeration indicating what type of action is contained in the payload.
        type: string
        enum:
          - InstanceStart
          - InstanceReset
          - InstanceHalt
          - InstanceDeviceDetach
      # Note that Attach is implicit in device create (PUT)
      instance_device_detach_action:
          $ref: '#/definitions/InstanceDeviceDetachAction'
      # Timestamp generated by FC - output only
      timestamp:
        type: string

  InstanceDeviceDetachAction:
    type: object
    required:
      - device_type
      - device_resource_id
    properties:
      device_type:
        type: string
        enum:
          - "drive"
          - "network-iface"
          - "vsock"
      device_resource_id:
        type: string
        minLength: 1
        maxLength: 64
      # If true then tear out device without guest cooperation
      force:
        type: boolean
  Error:
    properties:
      faultMessage:
        type: string
        description: A description of the error condition.
