swagger: "2.0"
info:
  title: Firecracker Devices API
  description: The devices section of the Firecracker API.
  version: experimental
  termsOfService: ""
  contact:
    email: "acatan@amazon.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

host: "localhost"
basePath: "/"

schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /drives:
    get:
      summary: "All guest drives"
      description: "Returns list of guest storage drives."
      operationId: "getGuestDrives"
      responses:
        200:
          description: List of guest drives
          schema:
            type: array
            items:
              $ref: "#/definitions/Drive"
        default:
          description: Internal server error.
          schema:
            $ref: '#/definitions/Error'
  /drives/{drive_id}:
    get:
      summary: "Get guest drive by 'drive_id' path parameter."
      operationId: "getGuestDriveByID"
      parameters:
      - name: "drive_id"
        in: path
        description: "The id of the guest drive."
        required: true
        type: string
      responses:
        200:
          description: Specified drive.
          schema:
            $ref: "#/definitions/Drive"
        404:
          description: Drive does not exist.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Internal server error.
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: "Creates new drive with ID specified by 'drive_id' path parameter. If drive with specified ID
                already exists, updates its state based on new input. May fail if update is not possible."
      operationId: "putGuestDriveByID"
      parameters:
      - name: "drive_id"
        in: path
        description: "The id of the guest drive."
        required: true
        type: string
      - name: "body"
        in: body
        description: "Guest drive properties"
        required: true
        schema:
          $ref: "#/definitions/Drive"
      responses:
        201:
          description: Drive created.
        204:
          description: Drive updated.
        400:
          description: Drive cannot be created due to bad input.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Internal server error.
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: "Deletes drive with ID specified by 'drive_id' path parameter.
                Will clean up any resources associated with this drive."
      operationId: "deleteGuestDriveByID"
      parameters:
      - name: "drive_id"
        in: path
        description: "The id of guest drive to delete."
        required: true
        type: string
      responses:
        202:
          description: Drive deleted.
        default:
          description: Internal server error.
          schema:
            $ref: '#/definitions/Error'
  /drives/{drive_id}/limiters:
    get:
      summary: Retrieves list of limiters IDs currently applied to the drive with 'drive_id'.
      operationId: "getLimitersForGuestDrive"
      parameters:
      - name: "drive_id"
        in: path
        description: "The id of the guest drive to get limiters for."
        required: true
        type: string
      responses:
        200:
          description: List of limiters IDs currently applied to this drive.
          schema:
            type: array
            items:
              type: integer
              format: int32
        404:
          description: Drive does not exist.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Internal server error.
          schema:
            $ref: '#/definitions/Error'
  /drives/{drive_id}/limiters/{limiter_id}:
    put:
      summary: Applies limiter 'limiter_id' to drive 'drive_id'
      operationId: applyLimiterToDrive
      parameters:
      - name: "drive_id"
        in: path
        description: "The id of the guest drive to apply limiter 'limiter_id' to."
        required: true
        type: string
      - name: "limiter_id"
        in: path
        description: "The id of the limiter to be applied to drive 'drive_id'."
        required: true
        type: string
      responses:
        200:
          description: Limiter applied.
        400:
          description: Limiter cannot be applied due to bad input.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Internal server error.
          schema:
            $ref: '#/definitions/Error'

  /network-interfaces:
    get:
      summary: "All guest network interfaces"
      description: "Returns list of guest network interfaces."
      operationId: "getGuestNetworkInterfaces"
      responses:
        205:
          description: List of guest network interfaces
          schema:
            type: array
            items:
              $ref: "#/definitions/NetworkInterface"
        default:
          description: Internal server error.
          schema:
            $ref: '#/definitions/Error'
  /network-interfaces/{iface_id}:
    get:
      summary: "Get guest network interface by 'iface_id' path parameter."
      operationId: "getGuestNetworkInterfaceByID"
      parameters:
      - name: "iface_id"
        in: path
        description: "The id of the guest network interface."
        required: true
        type: string
      responses:
        205:
          description: Specified network interface.
          schema:
            $ref: "#/definitions/NetworkInterface"
        404:
          description: Network interface does not exist.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Internal server error.
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: "Creates new network interface with ID specified by 'iface_id' path parameter.
                If network interface with specified ID already exists,
                updates its state based on new input. May fail if update is not possible."
      operationId: "putGuestNetworkInterfaceByID"
      parameters:
      - name: "iface_id"
        in: path
        description: "The id of the guest network interface."
        required: true
        type: string
      - name: "body"
        in: body
        description: "Guest network interface properties"
        required: true
        schema:
          $ref: "#/definitions/NetworkInterface"
      responses:
        201:
          description: Network interface created.
        400:
          description: Network interface cannot be created due to bad input.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Internal server error.
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: "Deletes network interface with ID specified by 'iface_id' path parameter.
                Will clean up any resources associated with this network interface."
      operationId: "deleteGuestNetworkInterfaceByID"
      parameters:
      - name: "iface_id"
        in: path
        description: "The id of guest network interface to delete."
        required: true
        type: string
      responses:
        202:
          description: Network interface deleted.
        default:
          description: Internal server error.
          schema:
            $ref: '#/definitions/Error'

definitions:
  DeviceState:
    type: string
    enum:
      - "attached"
      - "detaching"
      - "detached"
  Drive:
    type: object
    required:
      - drive_id
    properties:
      drive_id:
        type: string
      path_on_host:
        type: string
        description: "host level path for the guest drive"
      state:
        $ref: '#/definitions/DeviceState'
  NetworkInterface:
    type: object
    required:
      - iface_id
    properties:
      iface_id:
        type: string
      mac:
        type: string
      path_on_host:
        type: string
        description: "host level path for the guest network interface"
      state:
        $ref: '#/definitions/DeviceState'

  Error:
    properties:
      faultMessage:
        type: string
        description: A description of the error condition.
