[package]
name = "rebase_snap"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"
build = "../../build.rs"
license = "Apache-2.0"

[dependencies]
libc = ">=0.2.39"
vmm-sys-util = ">=0.8.0"

utils = { path = "../utils" }