[package]
name = "clippy-tracing"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "clippy-tracing"
bench = false

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
itertools = "0.12.0"
proc-macro2 = { version = "1.0.70", features = ["span-locations"] }
quote = "1.0.28"
syn = { version = "2.0.39", features = ["full", "extra-traits", "visit", "visit-mut", "printing"] } 
walkdir = "2.3.3"

[dev-dependencies]
uuid = { version = "1.6.1", features = ["v4"] }
